/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_prg2_josueham;

import java.awt.Color;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SKX Kafei
 */
public class Main extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios = new ArrayList();
    ArrayList<Alumno> alumnos = new ArrayList();
     ArrayList<Maestro> maestros = new ArrayList();
     Registro registro = new Registro("registro", "admin", "Registro", "Activa",  new Date().from(Instant.now()));
    
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuRegistro = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        TabbedRegistro = new javax.swing.JTabbedPane();
        PanelCRUDAlum = new javax.swing.JPanel();
        CirculoIzq = new javax.swing.JLabel();
        CirculoDer = new javax.swing.JLabel();
        lb_usernameCrud = new javax.swing.JLabel();
        FieldUsernameAlum = new javax.swing.JTextField();
        lb_contra = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        lb_tipo = new javax.swing.JLabel();
        Rbtn_alumno = new javax.swing.JRadioButton();
        Rbtn_maestro = new javax.swing.JRadioButton();
        btn_tipoUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_estado = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lb_nomAlum = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        lb_carrera = new javax.swing.JLabel();
        FieldCarrera = new javax.swing.JTextField();
        PNAsignarMaes = new javax.swing.JPanel();
        PNMatricularAlum = new javax.swing.JPanel();
        PanelClases = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        FondoUnitec = new javax.swing.JLabel();
        btngrupoUsuarios = new javax.swing.ButtonGroup();
        TabbedPanePrincipal = new javax.swing.JTabbedPane();
        PanelLogIn = new javax.swing.JPanel();
        Portal = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        FieldUsername = new javax.swing.JTextField();
        lb_password = new javax.swing.JLabel();
        PField_Contra = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        PanelAyuda = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        MenuRegistro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabbedRegistro.setForeground(new java.awt.Color(255, 255, 255));
        TabbedRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabbedRegistro.setName(""); // NOI18N

        PanelCRUDAlum.setBackground(new java.awt.Color(96, 150, 180));
        PanelCRUDAlum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CirculoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5886792.png"))); // NOI18N
        PanelCRUDAlum.add(CirculoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CirculoDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/5886792.png"))); // NOI18N
        PanelCRUDAlum.add(CirculoDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, -1));

        lb_usernameCrud.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        lb_usernameCrud.setForeground(new java.awt.Color(255, 255, 255));
        lb_usernameCrud.setText("Username");
        PanelCRUDAlum.add(lb_usernameCrud, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 20));
        PanelCRUDAlum.add(FieldUsernameAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, 40));

        lb_contra.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        lb_contra.setForeground(new java.awt.Color(255, 255, 255));
        lb_contra.setText("Contraseña");
        PanelCRUDAlum.add(lb_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));
        PanelCRUDAlum.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, 40));

        lb_tipo.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        lb_tipo.setForeground(new java.awt.Color(255, 255, 255));
        lb_tipo.setText("Tipo de Usuario");
        PanelCRUDAlum.add(lb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        btngrupoUsuarios.add(Rbtn_alumno);
        Rbtn_alumno.setText("Alumno");
        PanelCRUDAlum.add(Rbtn_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        btngrupoUsuarios.add(Rbtn_maestro);
        Rbtn_maestro.setText("Maestro");
        PanelCRUDAlum.add(Rbtn_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        btn_tipoUser.setText("->");
        btn_tipoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tipoUserActionPerformed(evt);
            }
        });
        PanelCRUDAlum.add(btn_tipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Nacimiento");
        PanelCRUDAlum.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        lb_estado.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        lb_estado.setForeground(new java.awt.Color(255, 255, 255));
        lb_estado.setText("Estado de la cuenta");
        PanelCRUDAlum.add(lb_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));
        PanelCRUDAlum.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 120, 40));

        lb_nomAlum.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        lb_nomAlum.setText("Nombre");
        PanelCRUDAlum.add(lb_nomAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));
        PanelCRUDAlum.add(FieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 80, 40));

        lb_carrera.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        lb_carrera.setText("Carrera");
        PanelCRUDAlum.add(lb_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));
        PanelCRUDAlum.add(FieldCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 80, 30));

        TabbedRegistro.addTab("CRUD Usuarios", new javax.swing.ImageIcon(getClass().getResource("/agregar-usuario.png")), PanelCRUDAlum); // NOI18N

        javax.swing.GroupLayout PNAsignarMaesLayout = new javax.swing.GroupLayout(PNAsignarMaes);
        PNAsignarMaes.setLayout(PNAsignarMaesLayout);
        PNAsignarMaesLayout.setHorizontalGroup(
            PNAsignarMaesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        PNAsignarMaesLayout.setVerticalGroup(
            PNAsignarMaesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        TabbedRegistro.addTab("Asignar Maestros", new javax.swing.ImageIcon(getClass().getResource("/teacher.png")), PNAsignarMaes); // NOI18N

        javax.swing.GroupLayout PNMatricularAlumLayout = new javax.swing.GroupLayout(PNMatricularAlum);
        PNMatricularAlum.setLayout(PNMatricularAlumLayout);
        PNMatricularAlumLayout.setHorizontalGroup(
            PNMatricularAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        PNMatricularAlumLayout.setVerticalGroup(
            PNMatricularAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        TabbedRegistro.addTab("Matricular Alumnos", new javax.swing.ImageIcon(getClass().getResource("/register.png")), PNMatricularAlum); // NOI18N

        PanelClases.setBackground(new java.awt.Color(96, 150, 180));
        PanelClases.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabbedRegistro.addTab("CRUD Clases", new javax.swing.ImageIcon(getClass().getResource("/atom.png")), PanelClases); // NOI18N

        jPanel1.add(TabbedRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 1060, 420));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/turn-left.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        FondoUnitec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo UNITEC.jpeg"))); // NOI18N
        jPanel1.add(FondoUnitec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MenuRegistro.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelLogIn.setBackground(new java.awt.Color(0, 51, 102));
        PanelLogIn.setForeground(new java.awt.Color(255, 255, 255));
        PanelLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Portal.setFont(new java.awt.Font("Calisto MT", 1, 42)); // NOI18N
        Portal.setForeground(new java.awt.Color(255, 255, 255));
        Portal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diamante_resized.png"))); // NOI18N
        Portal.setText("Portal");

        lb_username.setForeground(new java.awt.Color(255, 255, 255));
        lb_username.setText("Nombre de Usuario");

        FieldUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lb_password.setForeground(new java.awt.Color(255, 255, 255));
        lb_password.setText("Contraseña");

        PField_Contra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnIngresar.setBackground(new java.awt.Color(51, 102, 255));
        BtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLogInLayout = new javax.swing.GroupLayout(PanelLogIn);
        PanelLogIn.setLayout(PanelLogInLayout);
        PanelLogInLayout.setHorizontalGroup(
            PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogInLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Portal, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_username)
                    .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_password)
                    .addComponent(PField_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        PanelLogInLayout.setVerticalGroup(
            PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogInLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(Portal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lb_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lb_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(PField_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        TabbedPanePrincipal.addTab("Iniciar Sesion", PanelLogIn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelAyudaLayout = new javax.swing.GroupLayout(PanelAyuda);
        PanelAyuda.setLayout(PanelAyudaLayout);
        PanelAyudaLayout.setHorizontalGroup(
            PanelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAyudaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 606, Short.MAX_VALUE))
        );
        PanelAyudaLayout.setVerticalGroup(
            PanelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAyudaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 376, Short.MAX_VALUE))
        );

        TabbedPanePrincipal.addTab("Ayuda", PanelAyuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TabbedPanePrincipal)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
       if (FieldUsername.getText().equals(registro.getNombre()) && PField_Contra.getText().equals(registro.getPassword())) {
         abrir_MenuC();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario inexistente");
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(true);
       MenuRegistro.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_tipoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tipoUserActionPerformed
        if (Rbtn_alumno.isSelected()) {
            
        } else if (Rbtn_maestro.isSelected()){
            
        }
    }//GEN-LAST:event_btn_tipoUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

public void abrir_MenuC(){
    MenuRegistro.pack();
    MenuRegistro.setLocationRelativeTo(this);
    MenuRegistro.setVisible(true);
    FieldCarrera.setVisible(false);
    FieldNombre.setVisible(false);
    this.setVisible(false);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel CirculoDer;
    private javax.swing.JLabel CirculoIzq;
    private javax.swing.JTextField FieldCarrera;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTextField FieldUsername;
    private javax.swing.JTextField FieldUsernameAlum;
    private javax.swing.JLabel FondoUnitec;
    private javax.swing.JDialog MenuRegistro;
    private javax.swing.JPasswordField PField_Contra;
    private javax.swing.JPanel PNAsignarMaes;
    private javax.swing.JPanel PNMatricularAlum;
    private javax.swing.JPanel PanelAyuda;
    private javax.swing.JPanel PanelCRUDAlum;
    private javax.swing.JPanel PanelClases;
    private javax.swing.JPanel PanelLogIn;
    private javax.swing.JLabel Portal;
    private javax.swing.JRadioButton Rbtn_alumno;
    private javax.swing.JRadioButton Rbtn_maestro;
    private javax.swing.JTabbedPane TabbedPanePrincipal;
    private javax.swing.JTabbedPane TabbedRegistro;
    private javax.swing.JButton btn_tipoUser;
    private javax.swing.ButtonGroup btngrupoUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_carrera;
    private javax.swing.JLabel lb_contra;
    private javax.swing.JLabel lb_estado;
    private javax.swing.JLabel lb_nomAlum;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_tipo;
    private javax.swing.JLabel lb_username;
    private javax.swing.JLabel lb_usernameCrud;
    // End of variables declaration//GEN-END:variables
}
