/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_prg2_josueham;

import java.awt.Color;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SKX Kafei
 */
public class Main extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios = new ArrayList();
    ArrayList<Alumno> alumnos = new ArrayList();
     ArrayList<Maestro> maestros = new ArrayList();
     Registro registro = new Registro("registro", "admin", "Registro", "Activa",  new Date().from(Instant.now()));
    
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuRegistro = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        TabbedRegistro = new javax.swing.JTabbedPane();
        PanelCRUDAlum = new javax.swing.JPanel();
        CirculoIzq = new javax.swing.JLabel();
        CirculoAbajo = new javax.swing.JLabel();
        CirculoDer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        PanelCRUDMaes = new javax.swing.JPanel();
        PanelClases = new javax.swing.JPanel();
        PNAsignarMaes = new javax.swing.JPanel();
        PNMatricularAlum = new javax.swing.JPanel();
        PNCrudUsuarios = new javax.swing.JPanel();
        TabbedPanePrincipal = new javax.swing.JTabbedPane();
        PanelLogIn = new javax.swing.JPanel();
        Portal = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        FieldUsername = new javax.swing.JTextField();
        lb_password = new javax.swing.JLabel();
        PField_Contra = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        PanelAyuda = new javax.swing.JPanel();

        MenuRegistro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabbedRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabbedRegistro.setName(""); // NOI18N

        PanelCRUDAlum.setBackground(new java.awt.Color(96, 150, 180));
        PanelCRUDAlum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CirculoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/5886792.png"))); // NOI18N
        PanelCRUDAlum.add(CirculoIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, -1, -1));

        CirculoAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/5886792.png"))); // NOI18N
        PanelCRUDAlum.add(CirculoAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 714, -1, -1));

        CirculoDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/5886792.png"))); // NOI18N
        PanelCRUDAlum.add(CirculoDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, -1, -1));

        jLabel1.setText("jLabel1");
        PanelCRUDAlum.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jTextField1.setText("jTextField1");
        PanelCRUDAlum.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        TabbedRegistro.addTab("CRUD Alumnos", new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/estudiante.png")), PanelCRUDAlum); // NOI18N

        javax.swing.GroupLayout PanelCRUDMaesLayout = new javax.swing.GroupLayout(PanelCRUDMaes);
        PanelCRUDMaes.setLayout(PanelCRUDMaesLayout);
        PanelCRUDMaesLayout.setHorizontalGroup(
            PanelCRUDMaesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        PanelCRUDMaesLayout.setVerticalGroup(
            PanelCRUDMaesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );

        TabbedRegistro.addTab("CRUD Maestros", new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/teacher.png")), PanelCRUDMaes); // NOI18N

        javax.swing.GroupLayout PanelClasesLayout = new javax.swing.GroupLayout(PanelClases);
        PanelClases.setLayout(PanelClasesLayout);
        PanelClasesLayout.setHorizontalGroup(
            PanelClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        PanelClasesLayout.setVerticalGroup(
            PanelClasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );

        TabbedRegistro.addTab("CRUD Clases", new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/atom.png")), PanelClases); // NOI18N

        javax.swing.GroupLayout PNAsignarMaesLayout = new javax.swing.GroupLayout(PNAsignarMaes);
        PNAsignarMaes.setLayout(PNAsignarMaesLayout);
        PNAsignarMaesLayout.setHorizontalGroup(
            PNAsignarMaesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        PNAsignarMaesLayout.setVerticalGroup(
            PNAsignarMaesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );

        TabbedRegistro.addTab("Asignar Maestros", new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/rotation.png")), PNAsignarMaes); // NOI18N

        javax.swing.GroupLayout PNMatricularAlumLayout = new javax.swing.GroupLayout(PNMatricularAlum);
        PNMatricularAlum.setLayout(PNMatricularAlumLayout);
        PNMatricularAlumLayout.setHorizontalGroup(
            PNMatricularAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        PNMatricularAlumLayout.setVerticalGroup(
            PNMatricularAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );

        TabbedRegistro.addTab("Matricular Alumnos", new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/register.png")), PNMatricularAlum); // NOI18N

        javax.swing.GroupLayout PNCrudUsuariosLayout = new javax.swing.GroupLayout(PNCrudUsuarios);
        PNCrudUsuarios.setLayout(PNCrudUsuariosLayout);
        PNCrudUsuariosLayout.setHorizontalGroup(
            PNCrudUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        PNCrudUsuariosLayout.setVerticalGroup(
            PNCrudUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );

        TabbedRegistro.addTab("CRUD Usuarios", new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/agregar-usuario.png")), PNCrudUsuarios); // NOI18N

        jPanel1.add(TabbedRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 1060, 420));

        MenuRegistro.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelLogIn.setBackground(new java.awt.Color(0, 51, 102));
        PanelLogIn.setForeground(new java.awt.Color(255, 255, 255));
        PanelLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Portal.setFont(new java.awt.Font("Calisto MT", 1, 42)); // NOI18N
        Portal.setForeground(new java.awt.Color(255, 255, 255));
        Portal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_prg2_josueham/diamante_resized.png"))); // NOI18N
        Portal.setText("Portal");

        lb_username.setForeground(new java.awt.Color(255, 255, 255));
        lb_username.setText("Nombre de Usuario");

        FieldUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lb_password.setForeground(new java.awt.Color(255, 255, 255));
        lb_password.setText("Contraseña");

        PField_Contra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnIngresar.setBackground(new java.awt.Color(51, 102, 255));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLogInLayout = new javax.swing.GroupLayout(PanelLogIn);
        PanelLogIn.setLayout(PanelLogInLayout);
        PanelLogInLayout.setHorizontalGroup(
            PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogInLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PField_Contra)
                    .addComponent(Portal, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(lb_username)
                    .addComponent(FieldUsername)
                    .addComponent(lb_password)
                    .addComponent(BtnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        PanelLogInLayout.setVerticalGroup(
            PanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogInLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(Portal)
                .addGap(18, 18, 18)
                .addComponent(lb_username)
                .addGap(6, 6, 6)
                .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lb_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PField_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        TabbedPanePrincipal.addTab("Iniciar Sesion", PanelLogIn);

        javax.swing.GroupLayout PanelAyudaLayout = new javax.swing.GroupLayout(PanelAyuda);
        PanelAyuda.setLayout(PanelAyudaLayout);
        PanelAyudaLayout.setHorizontalGroup(
            PanelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        PanelAyudaLayout.setVerticalGroup(
            PanelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        TabbedPanePrincipal.addTab("Ayuda", PanelAyuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TabbedPanePrincipal)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
       if (FieldUsername.getText().equals(registro.getNombre()) && PField_Contra.getText().equals(registro.getPassword())) {
         abrir_MenuC();
        } else {
            JOptionPane.showMessageDialog(this, "Usuario inexistente");
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

public void abrir_MenuC(){
    MenuRegistro.pack();
    MenuRegistro.setLocationRelativeTo(this);
    MenuRegistro.setVisible(true);
    this.setVisible(false);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JLabel CirculoAbajo;
    private javax.swing.JLabel CirculoDer;
    private javax.swing.JLabel CirculoIzq;
    private javax.swing.JTextField FieldUsername;
    private javax.swing.JDialog MenuRegistro;
    private javax.swing.JPasswordField PField_Contra;
    private javax.swing.JPanel PNAsignarMaes;
    private javax.swing.JPanel PNCrudUsuarios;
    private javax.swing.JPanel PNMatricularAlum;
    private javax.swing.JPanel PanelAyuda;
    private javax.swing.JPanel PanelCRUDAlum;
    private javax.swing.JPanel PanelCRUDMaes;
    private javax.swing.JPanel PanelClases;
    private javax.swing.JPanel PanelLogIn;
    private javax.swing.JLabel Portal;
    private javax.swing.JTabbedPane TabbedPanePrincipal;
    private javax.swing.JTabbedPane TabbedRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_username;
    // End of variables declaration//GEN-END:variables
}
